remote_theme: jekyll/minima
title: ðŸ”® Enchanted Systems
author:
  name: alkoclick
  email: alkoclick@gmail.com
description: These are public thoughts from my Obsidian knowledge base, as well as any articles I have written
plugins:
  - jekyll-feed # Enables the RSS feed
  - jekyll-sitemap
  - jekyll-optional-front-matter
permalink: /:slug
future: true
minima:
  skin: solarized-light
  social_links:
    - { platform: github,  user_url: "https://github.com/alkoclick" }
    - { platform: linkedin,  user_url: "https://www.linkedin.com/in/alkoclick/" }
    - { platform: twitter,  user_url: "https://hachyderm.io/@alkoclick" }
header_pages:
  - me.md
  - blog.md
  - compensation.md
